import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const sfMono = localFont({
  src: "../assets/fonts/sf-mono/SFMonoRegular.otf",
  variable: "--font-sf-mono",
  preload: true,
  display: "swap",
});

const plus_jakarta_sans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Rashed Abdullah",
  description: "Generated by create next app",
};

import {
  Cursor,
  CursorFollow,
  CursorProvider,
  type CursorFollowProps,
} from "@/components/animate-ui/components/animate/cursor";
import Header from "@/components/common/header";

interface CursorDemoProps {
  global?: boolean;
  enableCursor?: boolean;
  enableCursorFollow?: boolean;
  side?: CursorFollowProps["side"];
  sideOffset?: number;
  align?: CursorFollowProps["align"];
  alignOffset?: number;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${plus_jakarta_sans.variable} ${sfMono.variable} antialiased text-primary`}
      >
        <CursorProvider global={true}>
          <Cursor />
          {/* <CursorFollow
            side={"bottom"}
            sideOffset={15}
            align={"end"}
            alignOffset={5}
          >
            About Me
          </CursorFollow> */}
          <Header />
          {children}
        </CursorProvider>
      </body>
    </html>
  );
}
